# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
# https://ckeditor.com/latest/samples/old/toolbar/toolbar.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - name: "styles"
                - items:
                    - 'Markdown'