twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        uploadDir: 'uploadDir'
        arbrePage: '@App\BusinessService\ArborescenceBS'

    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
